# Generated by Django 4.2.3 on 2023-12-07 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_certifyinginstitute_certificate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CertifyingInstitute",
            new_name="CertifyingInstitution",
        ),
    ]
